import './App.css'

function App() {
  // WhatsApp dos orçamentos: 041 98774-4267 -> código internacional 55 + DDD 41.
  const whatsappLink = 'https://wa.me/5541987744267?text=Ol%C3%A1!%20Quero%20pedir%20um%20or%C3%A7amento%20de%20impress%C3%A3o%203D.'

  // DADOS EDITÁVEIS: altere aqui os textos dos serviços que aparecem na página.
  const services = [
    { number: '01', title: 'Peças sob medida', text: 'Do seu rascunho ao protótipo funcional, com medidas e encaixes precisos.' },
    { number: '02', title: 'Miniaturas e presentes', text: 'Modelos cheios de personalidade para colecionar, presentear ou decorar.' },
    { number: '03', title: 'Pequenas séries', text: 'Produção local para marcas, eventos e criadores que precisam de agilidade.' },
  ]
  return (
    <main>
      <nav className="nav container" aria-label="Navegação principal"><a className="brand" href="#inicio"><span className="brand-mark">W</span> WITCHYK</a><div className="nav-links"><a href="#servicos">Serviços</a><a href="#avaliacoes">Avaliações</a></div><a className="nav-cta" href={whatsappLink} target="_blank" rel="noreferrer">Pedir orçamento <span>↗</span></a></nav>
      <section className="hero-section container" id="inicio"><div className="hero-copy"><p className="eyebrow">IMPRESSÃO 3D LOCAL · SOB MEDIDA</p><h1>Ideias que ganham <em>forma.</em></h1><p className="hero-description">Peças únicas, protótipos e objetos que começam na sua cabeça e chegam às suas mãos com acabamento impecável.</p><div className="hero-actions"><a className="button button-dark" href={whatsappLink} target="_blank" rel="noreferrer">Começar um projeto <span>↗</span></a><a className="text-link" href="#servicos">Conhecer serviços <span>↓</span></a></div><div className="hero-note"><span className="status-dot"></span> Respondemos em até 1 hora <span className="note-divider">•</span> Enviamos para todo o Brasil</div></div><div className="hero-image-wrap"><div className="image-stamp"><strong>EST. 2024</strong><span>Feito para durar</span></div><div className="image-caption"><span>WITCHYK</span><span>Matéria em movimento</span></div></div></section>
      <section className="ticker" aria-label="Diferenciais"><div>PROTOTIPAGEM RÁPIDA <span>✦</span> MATERIAIS DE QUALIDADE <span>✦</span> DESIGN QUE FUNCIONA <span>✦</span> PRODUÇÃO LOCAL <span>✦</span></div></section>
      <section className="section container" id="servicos"><div className="section-heading"><div><p className="eyebrow">O QUE FAZEMOS</p><h2>Do conceito à peça<br /><em>pronta para usar.</em></h2></div><p className="section-intro">A impressão 3D é só o começo. A gente escuta a ideia, resolve os detalhes e entrega algo que faz sentido no mundo real.</p></div><div className="services-grid">{services.map((service) => <article className="service" key={service.number}><span className="service-number">{service.number}</span><h3>{service.title}</h3><p>{service.text}</p><a href={whatsappLink} target="_blank" rel="noreferrer" aria-label={`Pedir orçamento para ${service.title}`}>Saiba mais <span>↗</span></a></article>)}</div></section>
      <section className="process-section container" id="processo"><div className="process-content"><p className="eyebrow">SEM COMPLICAÇÃO</p><h2>Seu próximo projeto<br /><em>começa aqui.</em></h2><p>Você manda a ideia. A gente cuida do resto: modelagem, material, impressão e acabamento.</p><a className="button button-lime" href={whatsappLink} target="_blank" rel="noreferrer">Falar com a WITCHYK <span>↗</span></a></div><div className="process-list"><div><span>01</span><strong>Conte sua ideia</strong><p>Um desenho, uma foto ou só uma descrição já basta.</p></div><div><span>02</span><strong>Receba a proposta</strong><p>Indicamos o melhor material, prazo e investimento.</p></div><div><span>03</span><strong>Receba sua peça</strong><p>Produzimos com cuidado e enviamos para você.</p></div></div></section>
      <section className="reviews-section" id="avaliacoes"><div className="container"><div className="section-heading reviews-heading"><div><p className="eyebrow">QUEM JÁ RECEBEU</p><h2>Feito com cuidado,<br /><em>aprovado por fãs.</em></h2></div><p className="section-intro">Cada peça sai daqui com atenção aos detalhes. Veja o que nossos clientes contam depois que o pedido chega.</p></div><div className="reviews-grid"><article className="review"><div className="stars">★★★★★</div><blockquote>“A peça ficou melhor do que eu imaginava. O acabamento fez toda a diferença.”</blockquote><p>Marina A. <span>·</span> São Paulo, SP</p></article><article className="review"><div className="stars">★★★★★</div><blockquote>“Meu filho amou o molde do Goku. Chegou bem embalado e antes do prazo.”</blockquote><p>Rafael M. <span>·</span> Campinas, SP</p></article><article className="review"><div className="stars">★★★★★</div><blockquote>“Mandei uma referência do Naruto e recebi uma miniatura linda. Recomendo muito.”</blockquote><p>Júlia R. <span>·</span> Curitiba, PR</p></article></div><a className="button button-dark review-cta" href={whatsappLink} target="_blank" rel="noreferrer">Pedir meu molde personalizado <span>↗</span></a></div></section>
      <footer className="footer container"><a className="brand" href="#inicio"><span className="brand-mark">W</span> WITCHYK</a><p>Objetos com intenção, impressos localmente.</p><div className="footer-links"><a href="mailto:oi@witchyk.com.br">oi@witchyk.com.br</a><a href={whatsappLink} target="_blank" rel="noreferrer">WhatsApp ↗</a><a href="#inicio">Instagram ↗</a></div><small>© 2024 WITCHYK. Feito com cuidado.</small></footer>
    </main>
  )
}

export default App
